{
    'name': 'Email Management System',
    'version': '18.0.1.0.0',
    'category': 'Emails',
    'sequence': 1,
    'author': 'Rolustech',
    'summary': 'Email Management System',
    'website': 'https://www.rolustech.com/',
    'description': """
    """,
    'depends': ['contacts', 'mail'],
    'data': [
        'views/email_record.xml',
        'views/menu_item.xml',
        'views/email_tags.xml',
        'views/fetchmail_fetch_wizard.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/email_templates.xml',
    ],
    'images': ['static/description/banner.gif'],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
